version: '3.8'

services:

  nextjs:
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
      - next:/app/.next
    command: sh -c "npx prisma db push && npm run dev"

volumes:
  node_modules:
  next: